-- מחברות שנוספו דרך ממשק הניהול באתר.
-- הקריאה ציבורית; כתיבה דורשת משתמש Supabase מחובר.
create table if not exists public.course_notebooks (
  id bigint generated by default as identity primary key,
  mode text not null check (mode in ('tours', 'theory', 'online')),
  subcategory text not null default '',
  title text not null,
  date text not null default '',
  guide text not null default '',
  places text not null default '',
  url text not null,
  owner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists course_notebooks_mode_idx
  on public.course_notebooks (mode, created_at);

alter table public.course_notebooks enable row level security;

drop policy if exists "course_notebooks_public_read" on public.course_notebooks;
create policy "course_notebooks_public_read" on public.course_notebooks
  for select using (true);

drop policy if exists "course_notebooks_authenticated_insert" on public.course_notebooks;
create policy "course_notebooks_authenticated_insert" on public.course_notebooks
  for insert to authenticated
  with check (auth.uid() = owner_id);

drop policy if exists "course_notebooks_owner_update" on public.course_notebooks;
create policy "course_notebooks_owner_update" on public.course_notebooks
  for update to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

drop policy if exists "course_notebooks_owner_delete" on public.course_notebooks;
create policy "course_notebooks_owner_delete" on public.course_notebooks
  for delete to authenticated
  using (auth.uid() = owner_id);

grant select on public.course_notebooks to anon, authenticated;
grant insert, update, delete on public.course_notebooks to authenticated;
grant usage, select on sequence public.course_notebooks_id_seq to authenticated;
