// Auto-generated by tools/import_course_exams.py — do not edit by hand.
import type { Exam } from "@/data/exams/types";
import practice1 from "@/data/exams/course/practice-1";
import practice2 from "@/data/exams/course/practice-2";
import practice3 from "@/data/exams/course/practice-3";
import practice4 from "@/data/exams/course/practice-4";
import practice5 from "@/data/exams/course/practice-5";
import focus1 from "@/data/exams/course/focus-1";
import focus2 from "@/data/exams/course/focus-2";
import focus3 from "@/data/exams/course/focus-3";
import focus4 from "@/data/exams/course/focus-4";
import focus5 from "@/data/exams/course/focus-5";
import topic1 from "@/data/exams/course/topic-1";
import topic2 from "@/data/exams/course/topic-2";
import topic3 from "@/data/exams/course/topic-3";
import topic4 from "@/data/exams/course/topic-4";
import topic5 from "@/data/exams/course/topic-5";

/** The course's own practice exams, newest set last. */
export const COURSE_EXAMS: Exam[] = [practice1, practice2, practice3, practice4, practice5, focus1, focus2, focus3, focus4, focus5, topic1, topic2, topic3, topic4, topic5];
