// Auto-generated by tools/import_course_exams.py from
// cfir94/morey-derech-quiz — the course's own practice exams. Do not edit by
// hand; edit them there and re-import.
import type { Exam } from "@/data/exams/types";

const exam: Exam = {
  "slug": "course-practice-3",
  "label": {
    "he": "מבחן תרגול 3",
    "en": "מבחן תרגול 3",
    "ar": "מבחן תרגול 3"
  },
  "date": "מבחן תרגול 3",
  "languages": [
    "he"
  ],
  "keySource": "course",
  "questions": [
    {
      "number": 1,
      "quizId": 20049,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "התרבויות הירמוכית ויריחו IX, שבהן הומצאו כלי החרס הראשונים, שייכות ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ניאולית קדם-קרמי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ניאולית קרמי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כלקולית מוקדם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פליאולית עליון",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "בניאולית הקרמי הומצאו והופצו כלי החרס הראשונים."
    },
    {
      "number": 2,
      "quizId": 20050,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מקדש עין גדי ותל צף מייצגים בעיקר איזו תופעה בכלקוליתית?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ראשית האמנות המערה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ראשית הבירוקרטיה והפולחן הממוסד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המצאת כלי החרס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ראשית הציד המאורגן",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "תל צף — בירוקרטיה מוקדמת; מקדש עין גדי — פולחן ממוסד."
    },
    {
      "number": 3,
      "quizId": 20051,
      "kind": "mc",
      "topic": "islam",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מתי מסתיים בערך העידן הפרהיסטורי באזורנו?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בערך 5,000 לפני זמננו (3,000 לפנה\"ס)",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בערך 1,200 לפנה\"ס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בערך 10,000 לפני זמננו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בערך 586 לפנה\"ס",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "עם המצאת הכתב במצרים ובמסופוטמיה."
    },
    {
      "number": 4,
      "quizId": 20052,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "תרבויות הכבארית, המושבית והנטופית שייכות לתקופה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הפליאוליתית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "האפי-פליאוליתית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הניאוליתית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הכלקוליתית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "תרבויות המזוהות עם התקופה האפי-פליאוליתית."
    },
    {
      "number": 5,
      "quizId": 20053,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "כלי בית ירח וכלי אבידוס, שיוצאו למצרים, מזוהים עם תקופת:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הברונזה הקדומה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה הביניימית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה התיכונה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברזל א'",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "מאפיינים את התרבות החומרית של הברונזה הקדומה."
    },
    {
      "number": 6,
      "quizId": 20054,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מכתבי אל-עמארנה, ארכיון דיפלומטי מצרי, מתעדים אירועים מתקופת:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הברונזה הקדומה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה הביניימית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה התיכונה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה המאוחרת",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "explanation": "כנען תחת שלטון אימפריאלי מצרי — הברונזה המאוחרת."
    },
    {
      "number": 7,
      "quizId": 20055,
      "kind": "mc",
      "topic": "state",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה מסמל אוסף איתורי השנהב שנמצא בארמון מגידו בשלהי הברונזה המאוחרת?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עוני כלכלי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פריחה אמנותית וייצוא יוקרתי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מלחמה מתמשכת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "נטישת העיר",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "מעיד על פריחה אמנותית וסחר יוקרה."
    },
    {
      "number": 8,
      "quizId": 20056,
      "kind": "mc",
      "topic": "christianity",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהי הסיבה המשוערת לקריסה האזורית סביב 1200–1150 לפנה\"ס?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מגפה עולמית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בצורות, רעידות אדמה ושינויי אקלים שהחלישו את מצרים והחיתים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פלישה מונגולית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "התפרצות געשית בגולן",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "החלשת האימפריות הובילה לנדידת 'גויי הים'."
    },
    {
      "number": 9,
      "quizId": 20057,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהי 'חפירת חתך', ולאיזה צורך היא משמשת?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חפירה בריבועים סטנדרטית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תעלה ארוכה וצרה לקישור שטחים או איתור אלמנטים לאורך מדרון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שיטת סקר ללא חפירה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שיטת סינון רטוב",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "כמו זו של קתלין קניון בעיר דוד."
    },
    {
      "number": 10,
      "quizId": 20058,
      "kind": "mc",
      "topic": "art-arch",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "סינון רטוב של עפר מאפשר לחשוף בעיקר:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שכבות סטרטיגרפיות עמוקות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פריטים זעירים שהיו עטופים בבוץ יבש, כמו מטבעות ופסיפס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תאריכי C14 מדויקים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מבנים אדריכליים שלמים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "כפי שנעשה בפרויקט סינון עפר הר הבית."
    },
    {
      "number": 11,
      "quizId": 20059,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהם שלושת ההיבטים המרכזיים של העבודה הארכיאולוגית?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חפירה, מכירה ותיעוד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מחקר, שימור והנחלה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סקר, חפירה וניקוי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תיארוך, מיון ותיוק",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "מחקר, שימור והנחלה (הנגשה לציבור)."
    },
    {
      "number": 12,
      "quizId": 20060,
      "kind": "mc",
      "topic": "second-temple",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "לאחר מרד בר כוכבא, שינו הרומאים את שם הפרובינציה 'יודיאה' ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "פלסטינה (סוריה ופלשתינה)",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כנען",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יהד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שאם",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "כדי למחוק את הזיקה היהודית לארץ."
    },
    {
      "number": 13,
      "quizId": 20061,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהו הגבול המקראי הרחב, המכונה 'הארץ המובטחת', לפי התיאור המקראי?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מנהר מצרים ועד נהר פרת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "התחומים הגאוגרפיים שבהם חלות מצוות התלויות בארץ",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גבולות מדינת ישראל בת ימינו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הגבול המנהלי של פרובינציית יודיאה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "הגבול המקראי הרחב, 'הארץ המובטחת', מתואר כמשתרע מנהר מצרים ועד נהר פרת."
    },
    {
      "number": 14,
      "quizId": 20062,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "לאיזו קבוצת עופות משתייך הנשר?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עופות מים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עופות דורסים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עופות שיר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עופות ניגרים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הנשר הוא דורס — דוגמה מרכזית לעוף דורס בארץ."
    },
    {
      "number": 15,
      "quizId": 20063,
      "kind": "mc",
      "topic": "state",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה קרה לאוכלוסיית הכטופה (ינשוף הדגים) בישראל?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "גדלה משמעותית בעשורים האחרונים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "נכחדה מהארץ בשנות ה-70 עקב ציד של אספנים וחוקרים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הוגדרה כמין פולש ומזיק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מעולם לא תועדה בישראל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הכטופה נכחדה מישראל בשנות ה-70 עקב ציד של אספנים וחוקרים."
    },
    {
      "number": 16,
      "quizId": 20064,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "תצורת ה'בתה' מאופיינת ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עצים גבוהים בני 5-8 מ'",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "צמחייה נמוכה ופתוחה עד גובה הברכיים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עצים מרווחים עם עשבים ביניהם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שיחים סבוכים עד גובה אדם",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "בתה היא הצורה הנמוכה ביותר — עשבים ושיחים קטנים עד גובה הברכיים."
    },
    {
      "number": 17,
      "quizId": 20065,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אלון מצוי ואלה ארץ-ישראלית הם עצים אופייניים לתצורת:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בתה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חורש",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מדבר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יער פארק בלבד",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "עצים מרכזיים בתצורת החורש הים-תיכוני."
    },
    {
      "number": 18,
      "quizId": 20066,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהו המשפט הנכון לגבי יער טבעי בישראל?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הוא נפוץ מאוד בכל אזורי הארץ",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הוא נדיר מאוד — דוגמה לו היא יער אודם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הוא קיים רק בנגב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אין יערות טבעיים כלל בישראל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "יער טבעי נדיר מאוד; יער אודם הוא דוגמה נזכרת."
    },
    {
      "number": 19,
      "quizId": 20067,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "סלע קשה במיוחד, מורכב מסיליקה, המופיע כעדשות כהות בתוך גיר וקירטון, הוא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "צור",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חוואר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "טוף",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קונגלומרט",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "צור — סיליקה, שבירה זכוכיתית חדה."
    },
    {
      "number": 20,
      "quizId": 20068,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "קונגלומרט (תלכיד) מזוהה בשטח על ידי:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "גבישים מיקרוסקופיים אחידים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שברי סלעים עגולים וחלקים מלוכדים יחד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תסיסה בחומצה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פסי מינרלים מקבילים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "חלוקי נחל עגולים מלוכדים — ערוצי נחל עתיקים."
    },
    {
      "number": 21,
      "quizId": 20069,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "המסה קרסטית (מערות נטיפים כמו מערת שורק) מתרחשת כאשר:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מי גשמים סופחים CO2 והופכים לחומצה חלשה הממיסה קלציט",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לבה מתקררת ומתכווצת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שכבת חוואר אטומה חוסמת מים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לוחות טקטוניים מחליקים זה לצד זה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "חומצה קלה ממיסה לאט את הקלציט בגיר/דולומיט."
    },
    {
      "number": 22,
      "quizId": 20070,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "סטייה ימנית בקו השבר הסורי-אפריקני גורמת ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שקיעה ויצירת אגן כמו ים המלח",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "התנגשות ולחיצה שמרימה קרקע — כמו הר החרמון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "היווצרות מכתשים בנגב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בליה קרסטית מואצת",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "לחיצה בין הלוחות מרימה את הקרקע — הר החרמון."
    },
    {
      "number": 23,
      "quizId": 20071,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה משותף לגרניט ולבזלת?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שניהם סלעי משקע ימיים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שניהם סלעים מגמתיים, מהתקררות מגמה/לבה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שניהם מכילים מאובנים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שניהם רכים ונמרחים ביד",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "ההבדל ביניהם הוא בקצב הקירור בלבד."
    },
    {
      "number": 24,
      "quizId": 20072,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהם שלוש משפחות הסלעים במחזור הסלעים?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "גיר, קירטון וצור",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מגמתיים, משקעיים ומטמורפיים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בזלת, גרניט וטוף",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פליאוליתי, ניאוליתי וכלקוליתי",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "מגמתיים, משקעיים ומטמורפיים."
    }
  ]
};

export default exam;
