// Auto-generated by tools/import_course_exams.py from
// cfir94/morey-derech-quiz — the course's own practice exams. Do not edit by
// hand; edit them there and re-import.
import type { Exam } from "@/data/exams/types";

const exam: Exam = {
  "slug": "course-practice-2",
  "label": {
    "he": "מבחן תרגול 2",
    "en": "מבחן תרגול 2",
    "ar": "מבחן תרגול 2"
  },
  "date": "מבחן תרגול 2",
  "languages": [
    "he"
  ],
  "keySource": "course",
  "family": "מבחן תרגול",
  "subjects": "חי, צומח, גיאולוגיה, פרהיסטוריה, מבוא לארכיאולוגיה וברונזה",
  "questions": [
    {
      "number": 1,
      "quizId": 20025,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "התקופה הפליאוליתית התיכונה מזוהה עם התרבות:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "האשלית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המוסטרית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הירמוכית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הכבארית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "התרבות המוסטרית התאפיינה בשיטת לבלואה ובקבורות מכוונות ראשונות."
    },
    {
      "number": 2,
      "quizId": 20026,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהי 'מהפכת המוצרים השניוניים' המזוהה עם התקופה הכלקוליתית?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ביות ראשוני של בעלי חיים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ניצול החיה לחלב, צמר וכוח עבודה מבלי להורגה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המצאת הכתב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מעבר לבתים מלבניים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "בכלקוליתית משלימים ניצול תוצרי החיה החיה ולא רק בשרה."
    },
    {
      "number": 3,
      "quizId": 20027,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "כלי האבן האופייני לפליאולית התחתון הוא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הסהרון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אבן היד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המיקרוליתים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הלהבונים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "אבן היד מזוהה עם התרבות האשלית בפליאולית התחתון."
    },
    {
      "number": 4,
      "quizId": 20028,
      "kind": "mc",
      "topic": "prehistory",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אילו כלים אופייניים לתקופה האפי-פליאוליתית?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "אבני יד גדולות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מיקרוליתים שקויטו לידיות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כלי חרס ראשונים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כלי נחושת",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "התקופה מזוהה עם מיקרוליתים — כלים זעירים ששולבו בידיות."
    },
    {
      "number": 5,
      "quizId": 20029,
      "kind": "mc",
      "topic": "bible",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "'תקופת האבות' המקראית מזוהה בדרך כלל עם ערי המלוכה הכנעניות העצמאיות של:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הברונזה הקדומה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה הביניימית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה התיכונה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הברונזה המאוחרת",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "explanation": "בברונזה התיכונה פורחות ערי-מדינה כנעניות עצמאיות."
    },
    {
      "number": 6,
      "quizId": 20030,
      "kind": "mc",
      "topic": "bible",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהו 'השער הסורי' שנבנה במגידו?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שער אבן חד-תאי מתקופת הברזל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שער בעל ארבעה תאים מלבני בוץ, עם קורות עץ לגמישות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מבנה קבורה כנעני",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מקדש הבמה העגולה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "השער הסורי נבנה בברונזה התיכונה, מלבני בוץ עם קורות עץ."
    },
    {
      "number": 7,
      "quizId": 20031,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מנהגי הקבורה האופייניים לתקופת הברונזה הביניימית כוללים:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קברי פיר, טומולי ודולמנים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מקדשי במה עגולה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קבורה בערים מבוצרות בלבד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שריפת גופות",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "עיקר הידע הארכאולוגי מגיע ממנהגי קבורה: קברי פיר, טומולי ודולמנים."
    },
    {
      "number": 8,
      "quizId": 20032,
      "kind": "mc",
      "topic": "islam",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "כיצד כבש תחותמס השלישי את מגידו בברונזה המאוחרת?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "באמצעות מצור ימי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בהפתעה, דרך מעבר עארונה הצר, ולאחר מכן מצור",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בעזרת ברית עם שליט העיר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "באמצעות רעידת אדמה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "תחותמס השלישי הפתיע את הקואליציה הכנענית דרך מעבר עארונה הצר."
    },
    {
      "number": 9,
      "quizId": 20033,
      "kind": "mc",
      "topic": "tourism",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "'עתיקה' לפי חוק העתיקות בישראל מוגדרת כחפץ שמקורו:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "לפני שנת 1948",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לפני שנת 1700 לספירה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לפני שנת 586 לפנה\"ס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לפני שנת 3300 לפנה\"ס",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "החוק מגדיר עתיקה כל חפץ שמקורו לפני שנת 1700 לספירה."
    },
    {
      "number": 10,
      "quizId": 20034,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהי מטרתם של חתכי העפר (בנקטים) בחפירה בריבועים?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "איסוף חרסים משטח האתר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ביקורת סטרטיגרפית ומעבר בטוח בשטח",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תיארוך מוחלט של הממצא",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "זיהוי טיפולוגי של כלי חרס",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "חתכי העפר משמשים למעקב אחר רצף השכבות ולמעבר בטוח."
    },
    {
      "number": 11,
      "quizId": 20035,
      "kind": "mc",
      "topic": "judaism",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מדוע נחשבת קרמיקה ל'פלסטיק של העת העתיקה'?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "כי היא עמידה במיוחד לאלפי שנים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כי האופנות המשתנות שלה הופכות אותה לכלי המרכזי לזיהוי כרונולוגי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כי היא החומר היחיד ששרד מהעת העתיקה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כי היא שימשה רק לאחסון מים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "שינויי הצורה והעיטור הופכים אותה לכלי המרכזי לתיארוך יחסי."
    },
    {
      "number": 12,
      "quizId": 20036,
      "kind": "mc",
      "topic": "geography",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "לפי איזו הגדרת גבול תוארה הארץ כמשתרעת 'מנהר מצרים ועד נהר פרת'?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הגבול המנהלי-פוליטי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הגבול המקראי הרחב (הארץ המובטחת)",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הגבול ההלכתי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הגבול הגיאוגרפי-פיזי",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "'הארץ המובטחת' היא הגדרה תיאורטית רחבה במקרא."
    },
    {
      "number": 13,
      "quizId": 20037,
      "kind": "mc",
      "topic": "judaism",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מדוע נחשבת ארץ ישראל ל'אוטוסטרדה' צבאית ומסחרית עתיקה?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בגלל מיקומה כגשר יבשתי בין שלוש יבשות — אסיה, אירופה ואפריקה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בגלל שפע נהרות גדולים החוצים אותה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בגלל אקלים נוח לתנועת צבאות בלבד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בגלל שהייתה בירת אימפריה גדולה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "explanation": "מיקומה כגשר יבשתי בין שלוש יבשות הפך אותה לנתיב מעבר קבוע (כמו 'דרך הים' ו'דרך המלך')."
    },
    {
      "number": 14,
      "quizId": 20038,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "איזה עוף דורס נדיר בעבר הפך היום לנפוץ בהרבה בישראל?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הדוכיפת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הדאה שחורת-הכתף",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הכטופה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הנשר",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הדאה שחורת-הכתף הפכה כיום לנפוצה בהרבה."
    },
    {
      "number": 15,
      "quizId": 20039,
      "kind": "mc",
      "topic": "state",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה קרה לאוכלוסיית הכטופה (ינשוף הדגים) בישראל?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "גדלה משמעותית בעשורים האחרונים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "נכחדה מהארץ בשנות ה-70 עקב ציד של אספנים וחוקרים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הוגדרה כמין פולש ומזיק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מעולם לא תועדה בישראל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הכטופה נכחדה מישראל בשנות ה-70 עקב ציד של אספנים וחוקרים."
    },
    {
      "number": 16,
      "quizId": 20040,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "כמה מ' בגובה מגיעים עצי 'החורש' הים-תיכוני בדרך כלל?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עד גובה הברכיים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עד גובה אדם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "5–8 מטרים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מעל 15 מטרים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "explanation": "חורש הוא מקבצי עצים נמוכים בגובה 5–8 מטרים."
    },
    {
      "number": 17,
      "quizId": 20041,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "הרקפת המצויה, לצד הכלנית, נחשבת ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "צמח מוגן שנעלם מהארץ",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פרח בולט ומוכר בנוף הישראלי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עץ אופייני לתצורת היער",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "צמח האופייני רק לתצורת הבתה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הרקפת המצויה נחשבת לפרח בולט בנוף הישראלי."
    },
    {
      "number": 18,
      "quizId": 20042,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהי התצורה המאופיינת בעצים מרווחים מאוד, שביניהם צומחים עשבים במקום צמחייה סבוכה?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חורש",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בתה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יער פארק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יער טבעי",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "explanation": "יער פארק — למשל יער יהודיה — עצים מרווחים עם עשבים ביניהם."
    },
    {
      "number": 19,
      "quizId": 20043,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "סלע פירורי קל שנוצר מאפר געשי, ובונה תלים געשיים ברמת הגולן, הוא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בזלת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סקוריה וטוף",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גרניט",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גיר",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "סקוריה וטוף בונים את התלים הגעשיים החרוטיים בגולן."
    },
    {
      "number": 20,
      "quizId": 20044,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אבן חול (Sandstone) נוצרת בעיקר מ:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שלדי יצורים ימיים שהתאבנו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גרגירי חול (בעיקר קוורץ) מלוכדים בתחמוצת ברזל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לבה שהתקררה במהירות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אפר געשי שהתלכד",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "גרגירי קוורץ מלוכדים בברזל, כמו בתמנע ובמכתשים."
    },
    {
      "number": 21,
      "quizId": 20045,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה ההבדל העיקרי בין קירטון לגיר?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קירטון תוסס בחומצה וגיר לא",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קירטון רך מאוד ונשבר בקלות, בעוד גיר קשה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גיר הוא סלע מגמתי וקירטון סלע משקע",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אין הבדל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "קירטון רך ונמרח כסיד, בעוד הגיר קשה יותר."
    },
    {
      "number": 22,
      "quizId": 20046,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מה גורם למעיינות חמים כמו בטבריה ובחמת גדר?",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בליה קרסטית של סלעי גיר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "נביעה של מים עמוקים לאורך קווי השבר בבקע הסורי-אפריקני",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "התכה של סלעי בזלת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מכתשי סחיפה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "מעיינות חמים נובעים לאורך קווי השבר של הבקע."
    },
    {
      "number": 23,
      "quizId": 20047,
      "kind": "mc",
      "topic": "geology",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "'אפקט השטיח' משמש כדימוי הדרכה להסבר:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מחזור הסלעים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כיצד סטייה בקו השבר יוצרת שקיעה או הרמה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "היווצרות מכתשים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "זיהוי סלעים בשטח",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "משיכת שטיח בעיקול יוצרת חור; דחיפתו יוצרת קמט."
    },
    {
      "number": 24,
      "quizId": 20048,
      "kind": "mc",
      "topic": "flora-fauna",
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "קצב תנועת הלוחות הטקטוניים, בהשוואה לתופעה מוכרת, דומה בעיקר ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קצב זרימת נהר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קצב גדילת ציפורניים — כמה סנטימטרים בשנה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קצב נפילת גשם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קצב זרימת לבה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "explanation": "הלוחות נעים בקצב איטי מאוד — כמו קצב גדילת ציפורניים."
    }
  ]
};

export default exam;
