// Auto-generated by tools/build_exams.py — do not edit by hand.
import type { Exam } from "@/data/exams/types";
import july2025 from "@/data/exams/july-2025";
import january2025 from "@/data/exams/january-2025";
import july2024 from "@/data/exams/july-2024";
import summer2023 from "@/data/exams/summer-2023";
import winter2022 from "@/data/exams/winter-2022";
import winter2021 from "@/data/exams/winter-2021";

/** Newest sitting first. */
export const EXAMS: Exam[] = [july2025, january2025, july2024, summer2023, winter2022, winter2021];

export function getExam(slug: string): Exam | undefined {
  return EXAMS.find((e) => e.slug === slug);
}
