// Auto-generated by tools/build_exams.py from the official answer key of this
// sitting, in every language it was published in. Each answer was checked
// against the editions that carry their own marking: the marked option has to
// sit at the same index in all of them. Do not edit by hand.
import type { Exam } from "@/data/exams/types";

const exam: Exam = {
  "slug": "summer-2019",
  "label": {
    "he": "מבחן רישוי — יוני 2019",
    "en": "Licensing Exam — June 2019",
    "ar": "امتحان الترخيص — حزيران 2019"
  },
  "date": "יוני 2019",
  "languages": [
    "he"
  ],
  "keySource": "derived",
  "questions": [
    {
      "number": 1,
      "quizId": 11001,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "סלע נארי מתפתח על סלע:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קירטון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בזלת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כורכר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דולומיט",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 2,
      "quizId": 11002,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "רב הקשור לשיקומה של טבריה הוא הרב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חיים אבולעפיה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חיים פרחי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חיים בן עטר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שמעון בן שטח",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 3,
      "quizId": 11003,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "נחל הנשפך לירדן:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "תנינים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תרצה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הבשור",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אלכסנדר",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 4,
      "quizId": 11004,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "הזור והע'ור הם מונחים הקשורים ל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ירקון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אברי הרבייה של הפרח",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ארכיטקטורה ממלוכית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ירדן",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 5,
      "quizId": 11005,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "משאב טבע המצוי בכמויות גדולות בישראל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "נפט",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גז",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יהלום",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ברזל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 6,
      "quizId": 11006,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "על פי ספר יהושע ירושלים היתה בנחלת שבט:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ראובן",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בנימין",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דן",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אף שבט",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 7,
      "quizId": 11007,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "כלניות במגוון צבעים ניתן למצוא בעיקר באזור:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עוטף עזה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הרי יהודה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "העמקים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הנגב",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "m"
    },
    {
      "number": 8,
      "quizId": 11008,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "עוף פולש לארץ בשנים האחרונות:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עוזניה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עורבני",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דררה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חסידה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 9,
      "quizId": 11009,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "נחל אוג נמצא ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "כרמל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מדבר יהודה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גליל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ערבה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 10,
      "quizId": 11010,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "גשר ג'ינדס נמצא על נחל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "איילון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אלכסנדר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שורק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לכיש",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 11,
      "quizId": 11011,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "פירוש המונח 'בד' במתקן בית הבד:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "אבן הרכב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אבן השכב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "משקולות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קורת העץ",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 12,
      "quizId": 11012,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "שריד מתקופת המקרא נמצא בחפירות ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "נבי סמואל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מגדלא",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גן לאומי תל באר שבע",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סוסיא",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 13,
      "quizId": 11013,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "קבורת כלבים בארץ בקנה מידה גדול יחסית נחשפה ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קיסריה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יפו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תל קסילה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אשקלון",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 14,
      "quizId": 11014,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אתר שלא הוכר כאתר מורשת עולמית:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מגידו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בית ג'ימל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מצדה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חצור",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 15,
      "quizId": 11015,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "שמה הקדום של קיסריה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מגדל סטרטון (מגדל שרשון)",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דיו קיסריה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דיוספוליס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דקהפוליס",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 16,
      "quizId": 11016,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אמת מים עות'מאנית נמצאת ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עבדת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מערת צדקיהו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קיבוץ לוחמי הגיטאות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חוף האקוודוקט",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 17,
      "quizId": 11017,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "המרד המאוחר מבין הבאים:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "המרד הגדול",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מרד התפוצות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מרד גאלוס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מרד בר כוכבא",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 18,
      "quizId": 11018,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "חורבן ירושלים בימי בית שני הושלם בחודש:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "תשרי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תמוז",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אלול",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "m"
    },
    {
      "number": 19,
      "quizId": 11019,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "עיר שהוקמה בסוף ימי הבית השני:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "טבריה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לוד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ציפורי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עכו",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 20,
      "quizId": 11020,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "השליט הפאטימי אל חאכם קשור בדת ה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בהאית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אחמדית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דרוזית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סלג'וקית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 21,
      "quizId": 11021,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מתחם צלבני גרמני בירושלים נמצא ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "שער שכם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מנזר ווירי גלילאי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "רובע היהודי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "רובע הארמני",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 22,
      "quizId": 11022,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "ראשית הזרם הקראי היה במאה ה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "7 לספירה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "8 לספירה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "9 לספירה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "10 לספירה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 23,
      "quizId": 11023,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מאפיין ארכיטקטוני מובהק של הבנייה הממלוכית:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "טריגליפים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מוקרנס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עמוד מרפק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כותרת קורינתית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 24,
      "quizId": 11024,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מייסדת \"חוות העלמות\" היתה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "רחל המשוררת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גולדה מאירסון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מניה שוחט",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חנה מייזל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 25,
      "quizId": 11025,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מהיישובים הראשונים שנוסדו בגוש עציון לפני קום המדינה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "אלון שבות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "רחלים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אפרת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קיבוץ רבדים",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 26,
      "quizId": 11026,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "שער נצחון רומי ניתן לראות ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "קיסריה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יודפת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ירושלים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בית גוברין",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 27,
      "quizId": 11027,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "הפלי\"ם הוא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הזרוע הצבאית הימית של הפלמ\"ח",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פלוגות ירושלים של האצ\"ל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שמה של ספינת מעפילים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פלוגות של הלח\"י שעסקו בהבאת מעפילים ארצה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 28,
      "quizId": 11028,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "המנורה מסמל מדינת ישראל לקוחה מ:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "מטבע של מתתיהו אנטיגונוס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המנורה בשער טיטוס",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המנורה במגדלא",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "המנורה ברובע ההרודיאני",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 29,
      "quizId": 11029,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "ההכרזה על הקמת מדינת ישראל היתה ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "כ\"ט בנובמבר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ד' באייר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ה' באייר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "15 במאי",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 30,
      "quizId": 11030,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "בתי קברות צבאיים בריטיים נמצאים ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "באר שבע ורמלה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ירושלים ואשדוד",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חיפה וקצרין",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עזה וניצנה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 31,
      "quizId": 11031,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "במפת מידבא לא נמצא בירושלים את:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הקארדו המזרחי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כנסיית הגייה ציון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חומת העיר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מקדש יופיטר על הר הבית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 32,
      "quizId": 11032,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "רצח ראש הממשלה יצחק רבין היה בשנת:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "1993",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "1994",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "1995",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "1996",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 33,
      "quizId": 11033,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "שתולה וזרעית הוקמו כ:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ישובי חומה ומגדל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מצפים בצפון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מושבים בגליל",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מוצבי צה\"ל",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "l"
    },
    {
      "number": 34,
      "quizId": 11034,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אתר הדורש תיאום בטחוני לצורך הביקור בו:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "סרטבא",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הר הבית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שילה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "עין קשתות (אום אל קנאטיר)",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "l"
    },
    {
      "number": 35,
      "quizId": 11035,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "חוקר ארץ ישראל במאה ה-19:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ריכרד קאופמן",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קונרד שיק",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אריק מנדלסון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יגאל ידין",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 36,
      "quizId": 11036,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "טובא זנגריה הוא ישוב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בדואי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "צ'רקסי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "דרוזי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שיעי",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 37,
      "quizId": 11037,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "אחרון המלכים ביהודה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "אחזיהו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יאשיהו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "צדקיהו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יהויכין",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 38,
      "quizId": 11038,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מס מיוחד שהוטל על יהודים תחת שלטון האיסלאם:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ג'יזיה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "טאבו",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ד'ימי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ג'יפתליק",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 39,
      "quizId": 11039,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "שטריימל הוא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "פיוט לשבת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "כובע חסידי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תיק לספר תורה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חגורה למעיל של חסיד",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 40,
      "quizId": 11040,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "פלמינגו ניתן לראות ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "עין תמיר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בריכות שלמה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ראש הנקרה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בריכות המלח מצפון לאילת",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 41,
      "quizId": 11041,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "\"שביל ישו\" ו\"דרך הבשורה\" עוברים באיזור:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "הר הזיתים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הר ציון",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בקעת כנרות",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "הבניאס",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "m"
    },
    {
      "number": 42,
      "quizId": 11042,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "חג \"הסיגד\" שייך לעדה ה:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "תימנית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אתיופית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קראית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "שומרונית",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 43,
      "quizId": 11043,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מספר חברי הכנסת בכנסת ישראל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "70",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "71",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "100",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "120",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 44,
      "quizId": 11044,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "\"עיד אל אדחא\" מתקיים:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "בקיץ",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "בחורף",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "באביב",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "לא בעונה קבועה",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    },
    {
      "number": 45,
      "quizId": 11045,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מסע נפוליאון לארץ ישראל היה ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "סוף המאה ה-17",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סוף המאה ה-18",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "סוף המאה ה-19",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ראשית המאה ה-20",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 46,
      "quizId": 11046,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "הקיסר פראנץ יוזף ביקר באזורנו לרגל:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חנוכת תעלת סואץ",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פריצת השער החדש",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חנוכת קו הרכבת החיג'אזית",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "פריצת שער יפו",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 0,
      "confidence": "h"
    },
    {
      "number": 47,
      "quizId": 11047,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מוזיאון \"המזגגה\" נמצא ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "ירוחם",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "חיפה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "קיבוץ נחשולים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "זכרון יעקב",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 48,
      "quizId": 11048,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "\"אקווריום ישראל\" נמצא ב:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חיפה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "אילת",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "ירושלים",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "תל אביב",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 2,
      "confidence": "h"
    },
    {
      "number": 49,
      "quizId": 11049,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "מוזיאון פרה היסטורי נמצא בקיבוץ:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "דפנה",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "מעיין ברוך",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "גינוסר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יראון",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 1,
      "confidence": "h"
    },
    {
      "number": 50,
      "quizId": 11050,
      "statement": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "statementAnswer": {
        "he": "",
        "en": "",
        "ar": ""
      },
      "question": {
        "he": "תחנת הרכבת בירושלים נקראת על שמו של הנשיא:",
        "en": "",
        "ar": ""
      },
      "answers": [
        {
          "text": {
            "he": "חיים ויצמן",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יצחק בן צבי",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "זלמן שזר",
            "en": "",
            "ar": ""
          }
        },
        {
          "text": {
            "he": "יצחק נבון בהצלחה!",
            "en": "",
            "ar": ""
          }
        }
      ],
      "correctIndex": 3,
      "confidence": "h"
    }
  ]
};

export default exam;
