"""
Build every licensing sitting we hold an answer key for, in all three of its
published languages, and write them into the site.

One script for the whole pipeline, because the two outputs must never drift:

  * src/data/exams/<slug>.ts — the full sitting for exam mode
  * src/data/exams/index.ts  — the list of sittings
  * src/data/quizzes/past-exams.ts — the same questions as single-question
    practice, in Hebrew, under the sitting's category

A question carries the same id in both, so a mistake made in exam mode joins
the ordinary review queue.

Which sittings are here is decided by one thing: **an official answer key.**
Summer 2020, summer 2022, summer 2024, winter 2025 and summer 2025 are held in
question form only, and a guessed answer would teach the wrong thing before a
licensing exam. They are not included.

Usage (from the repo root, with the PDF folders alongside):
    python3 tools/build_exams.py --pdfs /path/to/exam/pdfs
"""

import argparse
import json
import re
import sys
from pathlib import Path

from parse_exam import parse

ROOT = Path(__file__).resolve().parent.parent
QUIZ_FILE = ROOT / "src/data/quizzes/past-exams.ts"
EXAM_DIR = ROOT / "src/data/exams"

LANGS = ("he", "en", "ar")

# Sittings in chronological order. `id_base` is frozen per sitting: question ids
# are `id_base + item number`, so re-running this never renumbers a sitting that
# did not change, and a new sitting cannot collide with an old one.
SITTINGS = [
    {
        "slug": "winter-2021",
        "id_base": 1000,
        "category": "חורף 2021",
        "date": "חורף 2021",
        "label": {
            "he": "מבחן רישוי — חורף 2021",
            "en": "Licensing Exam — Winter 2021",
            "ar": "امتحان الترخيص — شتاء 2021",
        },
        "sources": {
            "he": "2021/multiple_choice_he_winter_2021.pdf",
            "en": "2021/multiple_choice_en_winter_2021.pdf",
            "ar": "2021/multiple_choice_ar_winter_2021.pdf",
        },
    },
    {
        "slug": "winter-2022",
        "id_base": 2000,
        "category": "חורף 2022",
        "date": "חורף 2022",
        "label": {
            "he": "מבחן רישוי — חורף 2022",
            "en": "Licensing Exam — Winter 2022",
            "ar": "امتحان الترخيص — شتاء 2022",
        },
        "sources": {
            "he": "2022/multiple_choice_he_winter_2022_resolved.pdf",
            "en": "2022/multiple_choice_en_winter_2022.pdf",
            "ar": "2022/multiple_choice_ar_winter_2022.pdf",
        },
    },
    {
        "slug": "summer-2023",
        "id_base": 3000,
        "category": "קיץ 2023",
        "date": "קיץ 2023",
        "label": {
            "he": "מבחן רישוי — קיץ 2023",
            "en": "Licensing Exam — Summer 2023",
            "ar": "امتحان الترخيص — صيف 2023",
        },
        "sources": {
            "he": "2023/AmericanQuestionnaireSolution Summer2023Hebrew.pdf",
            "en": "2023/2023-multiple-choice-english.pdf",
            "ar": "2023/2023-multiple-choice-arabic.pdf",
        },
    },
    {
        "slug": "july-2024",
        "id_base": 4000,
        "category": "יולי 2024",
        "date": "יולי 2024",
        "label": {
            "he": "מבחן רישוי — יולי 2024",
            "en": "Licensing Exam — July 2024",
            "ar": "امتحان الترخيص — تموز 2024",
        },
        "sources": {
            "he": "2024/answers-theory-test-july-2024-hebrew.pdf",
            "en": "2024/answers-theory-test-july-2024-english.pdf",
            "ar": "2024/answers-theory-test-july-2024-arabic.pdf",
        },
    },
    {
        "slug": "january-2025",
        "id_base": 5000,
        "category": "ינואר 2025",
        "date": "ינואר 2025",
        "label": {
            "he": "מבחן רישוי — ינואר 2025",
            "en": "Licensing Exam — January 2025",
            "ar": "امتحان الترخيص — كانون الثاني 2025",
        },
        "sources": {
            "he": "2025/january-test-part-a-hebrew.pdf",
            "en": "2025/january-test-part-a-english.pdf",
            "ar": "2025/january-test-part-a-arabic.pdf",
        },
    },
    {
        "slug": "july-2025",
        "id_base": 6000,
        "category": "יולי 2025",
        "date": "יולי 2025",
        "label": {
            "he": "מבחן רישוי — יולי 2025",
            "en": "Licensing Exam — July 2025",
            "ar": "امتحان الترخيص — تموز 2025",
        },
        "sources": {
            "he": "2025/Part1_jul2025_He.pdf",
            "en": "2025/Part1_jul2025_En.pdf",
            "ar": "2025/Part1_jul2025_Ar.pdf",
        },
    },
]

BRACKET_RE = re.compile(r"[\[(]([^\[\]()]{2,80})[\])]")

QUIZ_HEADER = """// Auto-generated by tools/build_exams.py from the official answer keys of the
// Ministry of Tourism licensing exams. Only the four-option comprehension half
// of each item is here, and only where the key marks exactly one answer. Do not
// edit by hand — see CLAUDE.md.
import type { Quiz } from "@/data/quizzes/types";

const quiz: Quiz = """

EXAM_HEADER = """// Auto-generated by tools/build_exams.py from the official answer key of this
// sitting, in every language it was published in. Each answer was checked
// against the editions that carry their own marking: the marked option has to
// sit at the same index in all of them. Do not edit by hand.
import type { Exam } from "@/data/exams/types";

const exam: Exam = """


def tidy(q):
    """
    Move the fill-in half's leftovers out of the comprehension question.

    The two halves are printed as one paragraph, and the bracketed answer the
    key adds does not always land where the line breaks: it can open the next
    line, dragging the tail of its own sentence with it. When an edition has no
    answer of its own and its question opens with a bracketed group, that group
    is that answer and anything before it belongs to the statement.
    """
    had = {lang: bool(text) for lang, text in q["statementAnswer"].items()}

    for lang, text in q["question"].items():
        elsewhere = any(v for l, v in had.items() if l != lang)
        m = BRACKET_RE.search(text)
        # A bracket the question opens with is misplaced wherever it appears;
        # one further in is only misplaced if this edition lost its answer.
        misplaced = m and (
            (not had[lang] and elsewhere and m.start() < 60)
            or (had[lang] and m.start() < 20)
        )
        if misplaced:
            q["statementAnswer"][lang] = m.group(1).strip()
            q["statement"][lang] = (
                q["statement"][lang] + " " + text[: m.start()]
            ).strip()
            text = text[m.end() :].strip()

        # An English question never opens mid-sentence, so a lowercase start is
        # the statement's own tail.
        if lang == "en" and text[:1].islower():
            i = text.find(". ")
            if 0 < i < 80:
                q["statement"][lang] = (
                    q["statement"][lang] + " " + text[: i + 1]
                ).strip()
                text = text[i + 2 :].strip()

        q["question"][lang] = text
    return q


def correct_index(item):
    if not item or not item.get("marksOk", True):
        return None
    marks = [i for i, a in enumerate(item["answers"]) if a["correct"]]
    return marks[0] if len(marks) == 1 else None


def build_sitting(sitting, pdf_dir):
    parsed, keyed = {}, {}
    for lang in LANGS:
        path = pdf_dir / sitting["sources"][lang]
        items, problems, found = parse(str(path), lang)
        parsed[lang] = {i["number"]: i for i in items}
        # An edition without a key still has a stray bold word or two. Its marks
        # are only worth cross-checking against when it marks most of the paper.
        marked = sum(1 for i in items if i["marksOk"])
        keyed[lang] = marked >= 0.6 * len(items) if items else False
        print(
            f"  {lang}: {len(items)}/{found} items"
            f", {marked} marked{' (key)' if keyed[lang] else ''}",
            file=sys.stderr,
        )

    if not keyed["he"]:
        raise SystemExit(f"{sitting['slug']}: the Hebrew edition carries no key")

    questions, dropped = [], []
    for n in sorted(parsed["he"]):
        idx = correct_index(parsed["he"][n])
        if idx is None:
            dropped.append((n, "no single marked answer in Hebrew"))
            continue

        conflict = False
        for lang in ("en", "ar"):
            if not keyed[lang]:
                continue
            other = correct_index(parsed[lang].get(n))
            if other is not None and other != idx:
                conflict = True
                print(
                    f"  ! Q{n}: {lang} marks answer {other + 1}, Hebrew {idx + 1}",
                    file=sys.stderr,
                )
        if conflict:
            dropped.append((n, "editions disagree on the answer"))
            continue

        def field(name):
            return {
                lang: (parsed[lang].get(n) or {}).get(name) or "" for lang in LANGS
            }

        answers = []
        for i in range(4):
            answers.append(
                {
                    "text": {
                        lang: (
                            parsed[lang][n]["answers"][i]["text"]
                            if n in parsed[lang]
                            else ""
                        )
                        for lang in LANGS
                    }
                }
            )

        questions.append(
            tidy(
                {
                    "number": n,
                    "quizId": sitting["id_base"] + n,
                    "statement": field("statement"),
                    "statementAnswer": field("statementAnswer"),
                    "question": field("question"),
                    "answers": answers,
                    "correctIndex": idx,
                }
            )
        )

    if dropped:
        print(f"  dropped: {dropped}", file=sys.stderr)

    # A language is offered only if it carries text for every question kept and
    # that text came out clean. A file that scatters zero-width letters beside
    # real ones (the 2023 Arabic edition) reads as a spray of one-letter words,
    # which no reader should be handed: two per cent of words is normal ("a",
    # "in", a digit), eighteen is a broken file.
    languages = []
    for lang in LANGS:
        if not all(
            q["question"][lang] and q["answers"][0]["text"][lang] for q in questions
        ):
            print(f"  {lang}: incomplete text, not offered", file=sys.stderr)
            continue
        words = [
            w
            for q in questions
            for text in [q["question"][lang]] + [a["text"][lang] for a in q["answers"]]
            for w in text.split()
        ]
        stray = sum(1 for w in words if len(w) == 1 and w.isalpha()) / max(1, len(words))
        if stray > 0.08:
            print(
                f"  {lang}: {stray:.0%} stray one-letter words, not offered",
                file=sys.stderr,
            )
            continue
        languages.append(lang)
    print(f"  -> {len(questions)} questions, languages {languages}", file=sys.stderr)

    return {
        "slug": sitting["slug"],
        "label": sitting["label"],
        "date": sitting["date"],
        "languages": languages,
        "questions": questions,
    }


def load_quiz():
    text = QUIZ_FILE.read_text()
    start = text.index("{", text.index("const quiz"))
    return json.loads(text[start : text.rindex("}") + 1])


def write_site(exams):
    EXAM_DIR.mkdir(parents=True, exist_ok=True)
    for exam in exams:
        (EXAM_DIR / f"{exam['slug']}.ts").write_text(
            EXAM_HEADER
            + json.dumps(exam, ensure_ascii=False, indent=2)
            + ";\n\nexport default exam;\n"
        )

    newest_first = list(reversed(exams))
    imports = "\n".join(
        f'import {slug_var(e["slug"])} from "@/data/exams/{e["slug"]}";'
        for e in newest_first
    )
    listed = ", ".join(slug_var(e["slug"]) for e in newest_first)
    (EXAM_DIR / "index.ts").write_text(
        "// Auto-generated by tools/build_exams.py — do not edit by hand.\n"
        'import type { Exam } from "@/data/exams/types";\n'
        f"{imports}\n\n"
        f"/** Newest sitting first. */\nexport const EXAMS: Exam[] = [{listed}];\n\n"
        "export function getExam(slug: string): Exam | undefined {\n"
        "  return EXAMS.find((e) => e.slug === slug);\n"
        "}\n"
    )

    # Rebuild the past-exams quiz: sittings we generate, plus any category that
    # came from elsewhere and still has no exam of its own.
    quiz = load_quiz()
    ours = {s["category"] for s in SITTINGS}
    kept = [q for q in quiz["questions"] if q["category"] not in ours]

    generated = []
    for sitting, exam in zip(SITTINGS, exams):
        for q in exam["questions"]:
            generated.append(
                {
                    "id": q["quizId"],
                    "question": q["question"]["he"],
                    "category": sitting["category"],
                    "answers": [
                        {
                            "text": a["text"]["he"],
                            "correct": i == q["correctIndex"],
                        }
                        for i, a in enumerate(q["answers"])
                    ],
                }
            )

    quiz["questions"] = generated + kept
    quiz["categories"] = [s["category"] for s in SITTINGS] + sorted(
        {q["category"] for q in kept}
    )
    QUIZ_FILE.write_text(
        QUIZ_HEADER
        + json.dumps(quiz, ensure_ascii=False, indent=2)
        + ";\n\nexport default quiz;\n"
    )
    print(
        f"\npast-exams quiz: {len(generated)} generated + {len(kept)} kept",
        file=sys.stderr,
    )


def slug_var(slug):
    parts = slug.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdfs", default=".", help="folder holding the exam PDF folders")
    args = ap.parse_args()

    pdf_dir = Path(args.pdfs)
    exams = []
    for sitting in SITTINGS:
        print(f"{sitting['slug']}:", file=sys.stderr)
        exams.append(build_sitting(sitting, pdf_dir))

    write_site(exams)


if __name__ == "__main__":
    main()
