"""
Turn one built exam (build_exam.py's JSON) into the site's data modules.

Writes two things from the same source, so the exam and the practice quiz can
never drift apart:

  * src/data/exams/<slug>.ts — the full sitting, three languages, for exam mode
  * the exam's block inside src/data/quizzes/past-exams.ts — the same questions
    as ordinary practice questions, in Hebrew

Each exam question carries the id its practice twin has (`quizId`), which is
what lets a mistake made in exam mode surface in "תרגול טעויות" like any other.

Usage (from the repo root, with the exam PDFs at hand):
    python3 tools/build_exam.py > /tmp/exam.json
    python3 tools/exam_to_site.py /tmp/exam.json
"""

import json
import re
import sys
from pathlib import Path

SLUG = "july-2024"
CATEGORY = "יולי 2024"
LABEL = {
    "he": "מבחן רישוי — יולי 2024",
    "en": "Licensing Exam — July 2024",
    "ar": "امتحان الترخيص — تموز 2024",
}

ROOT = Path(__file__).resolve().parent.parent
QUIZ_FILE = ROOT / "src/data/quizzes/past-exams.ts"
EXAM_FILE = ROOT / f"src/data/exams/{SLUG}.ts"

QUIZ_HEADER = """// Auto-generated from the Ministry of Tourism licensing exams (2021-2025).
// Only the four-option comprehension half of each exam item is included, and
// only where the official answer key marks exactly one answer. Do not edit by
// hand — see CLAUDE.md.
import type { Quiz } from "@/data/quizzes/types";

const quiz: Quiz = """

EXAM_HEADER = f"""// Auto-generated by tools/exam_to_site.py from the official answer keys of the
// July 2024 licensing exam, in all three languages it was published in.
// Every question was cross-checked across the three editions: the marked
// answer had to sit at the same index in each. Do not edit by hand.
import type {{ Exam }} from "@/data/exams/types";

const exam: Exam = """


def load_quiz():
    text = QUIZ_FILE.read_text()
    start = text.index("{", text.index("const quiz"))
    end = text.rindex("}") + 1
    return json.loads(text[start:end])


def main():
    items = json.loads(Path(sys.argv[1]).read_text())
    quiz = load_quiz()

    others = [q for q in quiz["questions"] if q["category"] != CATEGORY]
    # Where the sitting's block sat, counted among the questions that stay.
    at = len(
        [
            q
            for q in quiz["questions"][
                : next(
                    (
                        i
                        for i, x in enumerate(quiz["questions"])
                        if x["category"] == CATEGORY
                    ),
                    len(quiz["questions"]),
                )
            ]
            if q["category"] != CATEGORY
        ]
    )
    next_id = max(q["id"] for q in others) + 1

    practice, exam_questions = [], []
    for offset, item in enumerate(items):
        qid = next_id + offset
        practice.append(
            {
                "id": qid,
                "question": item["question"]["he"],
                "category": CATEGORY,
                "answers": [
                    {"text": a["text"]["he"], "correct": i == item["correctIndex"]}
                    for i, a in enumerate(item["answers"])
                ],
            }
        )
        exam_questions.append({"quizId": qid, **item})

    quiz["questions"] = others[:at] + practice + others[at:]
    if CATEGORY not in quiz["categories"]:
        quiz["categories"].append(CATEGORY)

    QUIZ_FILE.write_text(
        QUIZ_HEADER
        + json.dumps(quiz, ensure_ascii=False, indent=2)
        + ";\n\nexport default quiz;\n"
    )

    exam = {
        "slug": SLUG,
        "label": LABEL,
        "date": "יולי 2024",
        "questions": exam_questions,
    }
    EXAM_FILE.parent.mkdir(parents=True, exist_ok=True)
    EXAM_FILE.write_text(
        EXAM_HEADER
        + json.dumps(exam, ensure_ascii=False, indent=2)
        + ";\n\nexport default exam;\n"
    )

    print(f"{len(items)} questions -> {EXAM_FILE.name} and {CATEGORY} in the quiz")


if __name__ == "__main__":
    main()
