"""
Build the by-subject bank of real licensing-exam questions.

Input is tools/parse_efrat.py's output: the multiple-choice items the Ministry
of Tourism used in its licensing papers between 2000 and 2017, which Efrat
Nakash collected and sorted into 23 subjects, with the answer she proposes
highlighted in a companion PDF.

Why this is a bank of its own rather than extra questions folded into the
topical quizzes:

* **Provenance.** The questions are the Ministry's and are quoted as printed.
  The answers are Efrat's suggestion, not an official key — her own header says
  "אלה תשובות שאני מציעה". Folding them into a hand-written quiz would blur two
  different levels of certainty in one list. Here the whole quiz carries the
  caveat, exactly as the derived sittings do under /exams.
* **Regeneration.** This file is generated; the topical quizzes are curated
  through tools/quiz_edits/*.json. Mixing the two would make both unsafe to
  re-run.

The subjects go well beyond what the site has quizzes for — Second Temple,
Roman-Byzantine, Crusader, Muslim periods, the modern age, the Holocaust,
Israel's wars, minorities, water, safety, first aid — so this also fills in
whole areas of the syllabus that had nothing to practise against.

    python3 tools/parse_efrat.py --dir /workspace/sources/efrat --out /tmp/efrat_items.json
    python3 tools/import_exam_bank.py --items /tmp/efrat_items.json
"""

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from topics import topic_of  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/data/quizzes/exam-bank.ts"

# Question ids are ID_BASE + a running number, so a re-import never renumbers.
ID_BASE = 40000

# Her file names, in the order the syllabus teaches them, with the category
# label shown on the chip.
SUBJECTS = [
    ("prehistory", "פרהיסטוריה"),
    ("solomon-temple-biblical-archaeology", "בית ראשון — ברונזה, ברזל וארכיאולוגיה"),
    ("second-temple-period", "תקופת הבית השני"),
    ("roman-and-byzantine-period", "רומית-ביזנטית ומשנה ותלמוד"),
    ("arab-muslim-periods-and-islam", "התקופות המוסלמיות והאסלאם"),
    ("crusader-period", "התקופה הצלבנית"),
    ("modern-age", "העת החדשה — ציונות, מנדט ומדינה"),
    ("holocaust", "תולדות השואה"),
    ("israel-wars", "מלחמות ישראל"),
    ("judaism", "יהדות"),
    ("christianity", "נצרות"),
    ("minorities", "מיעוטים ופולקלור"),
    ("geology-and-geomorphology", "גיאולוגיה וגיאומורפולוגיה"),
    ("climate", "אקלים"),
    ("fauna", "החי בארץ ישראל"),
    ("flora", "הצומח בארץ ישראל"),
    ("areas-of-israel", "אזורים, דרכים וגבולות"),
    ("water", "הידרולוגיה ומשאבי מים"),
    ("nature-conservation-environment-eco-tourism", "שמירת טבע וסביבה"),
    ("state-of-israel", "מדינת ישראל"),
    ("tourism-in-israel", "תיירות בישראל"),
    ("safety-and-security", "ביטחון ובטיחות בטיולים"),
    ("first-aid", "עזרה ראשונה"),
]

HEADER = """// Auto-generated by tools/import_exam_bank.py — do not edit by hand.
//
// Real multiple-choice items from the Ministry of Tourism's licensing papers,
// 2000–2017, sorted by subject in Efrat Nakash's public collation:
// https://www.efratnakash.com/touring-israel-tips-h.asp
//
// The questions are the Ministry's, quoted as printed. The marked answers are
// Efrat's proposed solutions, NOT an official key — the quiz says so on screen.
import type { Quiz } from "@/data/quizzes/types";

const quiz: Quiz = """

# A stem this short is a parse casualty, not a question.
MIN_STEM = 12


def normalise(s: str) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    # Her files mark a blank with a run of dots or underscores.
    return re.sub(r"[._]{3,}", " ____ ", s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--items", required=True)
    args = ap.parse_args()

    raw = json.loads(Path(args.items).read_text())
    by_topic = {}
    for q in raw:
        by_topic.setdefault(q["topic"], []).append(q)

    unknown = set(by_topic) - {s for s, _ in SUBJECTS}
    if unknown:
        raise SystemExit(f"no label for subject(s): {sorted(unknown)}")

    questions, seen, next_id = [], set(), ID_BASE
    skipped = {"short": 0, "duplicate": 0}
    for slug, label in SUBJECTS:
        for item in sorted(by_topic.get(slug, []), key=lambda q: q["n"]):
            stem = normalise(item["question"])
            options = [normalise(o) for o in item["options"]]
            if len(stem) < MIN_STEM or any(not o for o in options):
                skipped["short"] += 1
                continue
            # The same item is sometimes filed under two subjects (Islam sits in
            # both the Muslim-periods file and the religions list).
            key = (stem, tuple(sorted(options)))
            if key in seen:
                skipped["duplicate"] += 1
                continue
            seen.add(key)
            next_id += 1
            questions.append(
                {
                    "id": next_id,
                    "question": stem,
                    "category": label,
                    "topic": topic_of(next_id, stem, options),
                    "source": "מבחני הרישוי 2000–2017 · אוסף אפרת נקש",
                    "answers": [
                        {"text": o, "correct": i == item["correctIndex"]}
                        for i, o in enumerate(options)
                    ],
                }
            )

    quiz = {
        "slug": "exam-bank",
        "label": "מאגר מבחני הרישוי לפי נושא",
        "notice": (
            "השאלות עצמן הן ממבחני הרישוי של משרד התיירות (2000–2017) ומצוטטות "
            "כלשונן. התשובות המסומנות הן פתרון שהציעה אפרת נקש ואינן מפתח רשמי "
            "— שווה לתרגל, וכשמשהו נראה לכם שגוי כדאי לאמת מול החומר."
        ),
        "categoryNoun": {"one": "נושא", "many": "נושאים"},
        "categories": [
            label for _, label in SUBJECTS if any(q["category"] == label for q in questions)
        ],
        "questions": questions,
    }
    OUT.write_text(
        HEADER + json.dumps(quiz, ensure_ascii=False, indent=2) + ";\n\nexport default quiz;\n"
    )

    print(f"{len(questions)} questions across {len(quiz['categories'])} subjects")
    print(f"skipped: {skipped['short']} unparseable, {skipped['duplicate']} duplicates")
    for _, label in SUBJECTS:
        n = sum(1 for q in questions if q["category"] == label)
        if n:
            print(f"   {label:44s} {n:4d}")


if __name__ == "__main__":
    main()
