"""
Import the course's own practice exams from cfir94/morey-derech-quiz.

That project is a single index.html holding three sets of five exams, written
for this course: "מבחן תרגול" (24 questions), "מבחן דגשי הרכז" and "מבחן נושאי"
(50 each, mixing multiple-choice with fill-in-the-blank). Every item carries an
explanation, which the Ministry's own papers never do.

They are the owner's own material, so unlike the resources directory they are
copied in — as exams under /exams, and as a question bank in the quizzes.

The exam JavaScript is read with node rather than a regex: the file is object
literals with unquoted keys, and a parser of our own would be the fragile part.

Usage:
    git clone --depth 1 https://github.com/cfir94/morey-derech-quiz /tmp/mdq
    python3 tools/import_course_exams.py --source /tmp/mdq/index.html
"""

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from topics import topic_of

ROOT = Path(__file__).resolve().parent.parent
EXAM_DIR = ROOT / "src/data/exams/course"
QUIZ_FILE = ROOT / "src/data/quizzes/course-bank.ts"

# The course taught two blocks and examined each of them separately. The five
# "מבחן תרגול" papers were written for the first block, the ten later ones for
# the second, so the subjects below are the syllabus of the block a paper
# covers — not a guess from its questions.
FIRST_BLOCK = "חי, צומח, גיאולוגיה, פרהיסטוריה, מבוא לארכיאולוגיה וברונזה"
SECOND_BLOCK = "יהדות, נצרות, ברזל וגבולות"

# (collection in the source, our slug prefix, what to call the family, subjects)
SETS = [
    ("EXAMS", "practice", "מבחן תרגול", FIRST_BLOCK),
    ("FOCUS_EXAMS", "focus", "מבחן דגשי הרכז", SECOND_BLOCK),
    ("TOPIC_EXAMS", "topic", "מבחן נושאי", SECOND_BLOCK),
]

# Question ids are `ID_BASE + running number` so a re-import never renumbers.
ID_BASE = 20000

EXTRACT_JS = """
const fs = require('fs');
let src = fs.readFileSync(process.argv[2], 'utf8');
const open = src.indexOf('<script');
src = src.slice(src.indexOf('>', open) + 1, src.indexOf('</script>', open));
// Keep the data only: everything up to the first line that touches the page.
const cut = src.search(/\\n\\s*(document|window|const state|let state)\\b/);
const data = cut > 0 ? src.slice(0, cut) : src;
const read = new Function(
  data +
    "\\nreturn {EXAMS: typeof EXAMS !== 'undefined' ? EXAMS : {}," +
    " FOCUS_EXAMS: typeof FOCUS_EXAMS !== 'undefined' ? FOCUS_EXAMS : {}," +
    " TOPIC_EXAMS: typeof TOPIC_EXAMS !== 'undefined' ? TOPIC_EXAMS : {}};",
);
process.stdout.write(JSON.stringify(read()));
"""


def read_source(path):
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(EXTRACT_JS)
        script = f.name
    out = subprocess.run(
        ["node", script, str(path)], capture_output=True, text=True, check=True
    )
    return json.loads(out.stdout)


def items_of(exam):
    """Both shapes the source uses: one `items` list, or `mc` plus `fill`."""
    if exam.get("items"):
        return exam["items"]
    return list(exam.get("mc", [])) + list(exam.get("fill", []))


def clean(text):
    """The fill-in questions carry a run of underscores where the blank is."""
    return re.sub(r"\s+", " ", re.sub(r"_{3,}", " ____ ", text)).strip()


def ts(value):
    return json.dumps(value, ensure_ascii=False)


EXAM_HEADER = """// Auto-generated by tools/import_course_exams.py from
// cfir94/morey-derech-quiz — the course's own practice exams. Do not edit by
// hand; edit them there and re-import.
import type { Exam } from "@/data/exams/types";

const exam: Exam = """

QUIZ_HEADER = """// Auto-generated by tools/import_course_exams.py from the course's own
// practice exams (cfir94/morey-derech-quiz). Every question here also appears
// inside one of the exams under /exams/course-*. Do not edit by hand.
import type { Quiz } from "@/data/quizzes/types";

const quiz: Quiz = """


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True, help="path to the project's index.html")
    args = ap.parse_args()

    source = read_source(Path(args.source))
    EXAM_DIR.mkdir(parents=True, exist_ok=True)

    exams, bank, next_id = [], [], ID_BASE
    for collection, prefix, family, subjects in SETS:
        for order, (key, raw) in enumerate(
            sorted(source.get(collection, {}).items(), key=lambda kv: int(kv[0])), 1
        ):
            slug = f"{prefix}-{order}"
            questions = []
            for n, item in enumerate(items_of(raw), 1):
                next_id += 1
                fill = item.get("type") == "fill"
                text = clean(item["q"])
                answers = [
                    {"text": {"he": o, "en": "", "ar": ""}}
                    for o in (item.get("options") or [])
                ]
                question = {
                    "number": n,
                    "quizId": next_id,
                    "kind": "fill" if fill else "mc",
                    "topic": topic_of(next_id, text, [o for o in item.get("options", [])]),
                    "statement": {"he": "", "en": "", "ar": ""},
                    "statementAnswer": {"he": "", "en": "", "ar": ""},
                    "question": {"he": text, "en": "", "ar": ""},
                    "answers": answers,
                    "correctIndex": -1 if fill else int(item["correct"]),
                    "explanation": item.get("exp", ""),
                }
                if fill:
                    question["answerText"] = item["answer"]
                questions.append(question)

                if not fill:
                    bank.append(
                        {
                            "id": next_id,
                            "question": text,
                            "category": item.get("topic", family),
                            "topic": question["topic"],
                            "explanation": item.get("exp", ""),
                            "answers": [
                                {"text": o, "correct": i == int(item["correct"])}
                                for i, o in enumerate(item["options"])
                            ],
                        }
                    )

            title = raw.get("title", f"{family} {order}")
            exam = {
                "slug": f"course-{slug}",
                "label": {"he": title, "en": title, "ar": title},
                "date": title,
                "languages": ["he"],
                "keySource": "course",
                "family": family,
                "subjects": subjects,
                "questions": questions,
            }
            (EXAM_DIR / f"{slug}.ts").write_text(
                EXAM_HEADER
                + json.dumps(exam, ensure_ascii=False, indent=2)
                + ";\n\nexport default exam;\n"
            )
            exams.append((slug, exam))
            print(
                f"{exam['slug']}: {len(questions)} questions"
                f" ({sum(1 for q in questions if q['kind'] == 'fill')} fill-in)",
                file=sys.stderr,
            )

    var = lambda slug: re.sub(r"-(\w)", lambda m: m.group(1).upper(), slug)
    (EXAM_DIR / "index.ts").write_text(
        "// Auto-generated by tools/import_course_exams.py — do not edit by hand.\n"
        'import type { Exam } from "@/data/exams/types";\n'
        + "\n".join(
            f'import {var(s)} from "@/data/exams/course/{s}";' for s, _ in exams
        )
        + "\n\n/** The course's own practice exams, newest set last. */\n"
        f"export const COURSE_EXAMS: Exam[] = [{', '.join(var(s) for s, _ in exams)}];\n"
    )

    categories = sorted({q["category"] for q in bank})
    quiz = {
        "slug": "course-bank",
        "label": "מאגר שאלות הקורס",
        "categoryNoun": {"one": "נושא", "many": "נושאים"},
        "categories": categories,
        "questions": bank,
    }
    QUIZ_FILE.write_text(
        QUIZ_HEADER
        + json.dumps(quiz, ensure_ascii=False, indent=2)
        + ";\n\nexport default quiz;\n"
    )
    print(
        f"\n{len(exams)} exams, {len(bank)} multiple-choice questions in the bank"
        f" across {len(categories)} subjects",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
