// Auto-generated by tools/fetch_efrat_links.py — do not edit by hand.
//
// A directory of links to Efrat Nakash's public course materials. Her site
// reserves all rights, so the site links to her pages and never copies them.
import type { ResourceGroup, Resource } from "@/data/resources-types";


/** The lists that answer a whole section of this site directly. */
export const FEATURED_RESOURCES: Resource[] = [
  { slug: "reports", title: "דוחות סיור לפי אתר", note: "דוח סיור לכל אתר וקטע דרך, מסודר לפי אזור — הבסיס לדוחות שכותבים בקורס.", url: "https://www.efratnakash.com/touring-israel-tips/list-of-tours-and-sites.asp" },
  { slug: "four-lines", title: "טבלת תמצית תכני הדרכה ב-4 שורות", note: "לכל אתר: ארבע שורות שאפשר להגיד עליו. בדיוק מה שנדרש בחלק ב' של המבחן בכתב.", url: "https://docs.google.com/document/d/1ZEBNS4PNhZiaQSanZHBL5D61Dxc4z_Z3VtNNF8EbhCw/edit?usp=sharing" },
  { slug: "routes", title: "מסלולי טיול — פתרונות חלק ב'", note: "כ-20 מסלולים בנויים לפי נושא, כתשובה לדוגמה לשאלת בניית המסלול.", url: "https://www.efratnakash.com/touring-israel-tips/list-of-tour-plans.asp" },
  { slug: "questions", title: "שאלות על נושאי הלימוד ופתרונן", note: "רשימת שאלות לחזרה עם התשובות, וקישורים לחידונים.", url: "https://docs.google.com/document/d/1wocBDJn9CqnjmXn-2i9O74AMWuR5P0abn1rPa6wDVFg/edit?usp=sharing" },
];

export const RESOURCE_GROUPS: ResourceGroup[] = [
  {
    slug: "history",
    title: "היסטוריה וארכאולוגיה",
    description: "סיכומי הרצאות לפי תקופה — מהפרהיסטוריה ועד ימינו.",
    items: [
      { title: "פרהיסטוריה בארץ ישראל", url: "https://docs.google.com/document/d/1USZJT7Jn4okKEgaza6bfFLbfLSJ6FUSD0w0qKPlkEQY/edit?usp=sharing" },
      { title: "תקופת הבית הראשון וארכאולוגיה של התקופות הקדומות", url: "https://docs.google.com/document/d/113uXIGouRz2HF9Ad0DfUFz_Hbp_maJCj3AGOaA9Hvfo/edit?usp=sharing" },
      { title: "תקופת הבית השני", url: "https://docs.google.com/document/d/12UEzTJAj1lnbBBxUPA3e_4Fju9L0AqzVVmI6SrO9X8c/edit?usp=sharing" },
      { title: "התקופה הרומית-ביזנטית, ארכאולוגיה קלאסית ויהודית", url: "https://docs.google.com/document/d/1_l62e2-qi-61dEZ9G1FMxjsVvfbEy4UkJocTdEUgtLY/edit?usp=sharing" },
      { title: "התקופה הערבית הקדומה", url: "https://docs.google.com/document/d/19oZPco0UaoDV-FAzc077R2BNGpohDm1ZcNrq6DBN0O4/edit?usp=sharing" },
      { title: "התקופה הצלבנית", url: "https://docs.google.com/document/d/1E1VKYVRT19ykJRNgtRL0iVfM1B2MbFRDW9t6ZumD5ig/edit?usp=sharing" },
      { title: "התקופה המוסלמית-ערבית השנייה", url: "https://docs.google.com/document/d/1BXZjSgP0V6kdihVf4u2kBB6SX3YYeSij4kLXriiJjh8/edit?usp=sharing" },
      { title: "העת החדשה", url: "https://docs.google.com/document/d/17WV-9umujOnu2RPloHsatC-0UCzSBlh384ZLudXdcc4/edit?usp=sharing" },
      { title: "תולדות השואה", url: "https://docs.google.com/document/d/1kCS6Cg2Wu2-hrBsiApY9337PAqbLaYDxi2eOkREY99c/edit?usp=sharing" },
      { title: "מלחמות ישראל", url: "https://docs.google.com/document/d/1J58y4hiAGzzSmpRM-06iyPEsg8LI6MMGfi-3KeWEGSc/edit?usp=sharing" },
      { title: "מדינת ישראל מהקמתה ועד היום", url: "https://docs.google.com/document/d/1GEorjB-NrfPnO1Q843FFGT_tuDyZd5Y1RhCyRTQfykM/edit?usp=sharing" },
      { title: "ירושלים לדורותיה", url: "https://docs.google.com/document/d/13dWXqUg3vYptUZybMbKOtJygXtPbqLHQgYOMYrPOHM0/edit?usp=sharing" },
    ],
  },
  {
    slug: "geography",
    title: "גאוגרפיה",
    description: "גבולות, דרכים, גאולוגיה, אקלים והחי והצומח של הארץ.",
    items: [
      { title: "מבוא לארץ ישראל – גבולות", url: "https://docs.google.com/document/d/1nSv1o0uUDg78PtHV0TChNmPTEZ8_dRMj_FeCFL3wdRo/edit?usp=sharing" },
      { title: "מבוא לארץ ישראל – דרכים", url: "https://docs.google.com/document/d/12RJ6BX1HSMBLwv8S76qm2rPqy4mBJkutwTnHatLeH9I/edit?usp=sharing" },
      { title: "גאולוגיה וגאומורפולוגיה", url: "https://docs.google.com/document/d/1npLgmJSp3lAOVG47QtaTMHcqcqYZ6NV5pu7Uqunu_Dw/edit?usp=sharing" },
      { title: "האקלים בארץ ישראל", url: "https://docs.google.com/document/d/1Is32JuL2eW7c-rgvbCKnn7_8PWs29xpY8vuT-jUhRII/edit?usp=sharing" },
      { title: "הצומח בארץ ישראל", url: "https://docs.google.com/document/d/1JhBq5EEjARruNM-GASgHXE7zTymXYIrct9DvTCcUB28/edit?usp=sharing" },
      { title: "החי בארץ ישראל", url: "https://docs.google.com/document/d/1HbFb93Hx4OgyDUjnP-LP2JqR3G9g-TizuVjiq_ojZ0w/edit?usp=sharing" },
      { title: "מושגי יסוד בטופוגרפיה", url: "https://docs.google.com/document/d/10x7BKxZ6tbzj-1Z4bSsLpp3gFW4fKtHC9XOF6t4Q1Ww/edit?usp=sharing" },
    ],
  },
  {
    slug: "religions",
    title: "דתות ומיעוטים",
    description: "שלוש הדתות והעדות שחיות בארץ.",
    items: [
      { title: "אסלאם", url: "https://docs.google.com/document/d/1wu4Gak-NGP9QRchoHu9FUzWoYURnRZwaFNU99CmyPCQ/edit?usp=sharing" },
      { title: "יהדות", url: "https://docs.google.com/document/d/1KM_ZdKJkXkm0rjNlXdCZmQsMvdZg8sRq59ntwfVOegk/edit?usp=sharing" },
      { title: "נצרות", url: "https://docs.google.com/document/d/11mCvlzEEE-5Vkvj1rKLzf4srcar8KilqjnZSCLoEeMA/edit?usp=sharing" },
      { title: "מיעוטים ופולקלור במדינת ישראל", url: "https://docs.google.com/document/d/1ROw5DUs_m3_VGlyusu6Jpe4fxFno_dDzKt01pRiWclc/edit?usp=sharing" },
    ],
  },
  {
    slug: "art",
    title: "אמנות ואדריכלות",
    description: "סגנונות בנייה לפי תקופה ולפי דת — מה רואים באתר ואיך מזהים.",
    items: [
      { title: "סגנונות אדריכליים ואמנותיים", url: "https://docs.google.com/document/d/1zA1lhcVsIVCkBtK4UWkfk6DVHmWa1HkOQw4jFJuPO-w/edit?usp=sharing" },
      { title: "אמנות ואדריכלות מוסלמית", url: "https://docs.google.com/document/d/1wu4Gak-NGP9QRchoHu9FUzWoYURnRZwaFNU99CmyPCQ/edit#heading=h.3qdjljgouvn7" },
      { title: "אמנות ואדריכלות נוצרית", url: "https://docs.google.com/document/d/11mCvlzEEE-5Vkvj1rKLzf4srcar8KilqjnZSCLoEeMA/edit#heading=h.1ad4yamc4tv7" },
      { title: "אדריכלות בתקופות ההלניסטית, רומית וביזנטית", url: "https://docs.google.com/document/d/1_l62e2-qi-61dEZ9G1FMxjsVvfbEy4UkJocTdEUgtLY/edit#heading=h.j1wpop288cxc" },
      { title: "אדריכלות בתקופה הצלבנית", url: "https://docs.google.com/document/d/1E1VKYVRT19ykJRNgtRL0iVfM1B2MbFRDW9t6ZumD5ig/edit#heading=h.tytoikhyl11h" },
    ],
  },
  {
    slug: "israel-today",
    title: "ישראל של היום",
    description: "משטר, כלכלה, מים, סביבה והסכסוך — הנושאים ה“לא-היסטוריים” של הבחינה.",
    items: [
      { title: "תולדות הסכסוך הישראלי-ערבי", url: "https://docs.google.com/document/d/1p_3bqgCEShJvFlELhEaakG8u4Tt1Nf9WmoKJ-3Ox9sw/edit?usp=sharing" },
      { title: "המשטר בישראל", url: "https://docs.google.com/document/d/1hW35KlcvXtz_jYzTAuwxvThroxIoK-f7k300xwNTz6g/edit?usp=sharing" },
      { title: "הידרולוגיה ומשאבי המים של ישראל", url: "https://docs.google.com/document/d/1WTcJ9ij3Yn5bnVByAVYTQdcCl8fI5U-HSMA8qzpi64A/edit?usp=sharing" },
      { title: "הכלכלה בישראל", url: "https://docs.google.com/document/d/1zvBoWGE1Fdph7Aiks97nsU7CI-oy7Tz1MAykpIzk_Kw/edit?usp=sharing" },
      { title: "שמירת טבע, איכות הסביבה ותיירות אקולוגית", url: "https://docs.google.com/document/d/1Hqoy0BTCtMyE7vlYL8dOWo7jTCuzBfGfcxabi6d3blU/edit?usp=sharing" },
      { title: "ביקורי תיירים ב\"שטחים\"", url: "https://docs.google.com/document/d/1NMGkX2SGPqZrpKWuDsC5hsfBvkig3rXoEEAFEIso3YM/edit?usp=sharing" },
    ],
  },
  {
    slug: "profession",
    title: "המקצוע עצמו",
    description: "מה שנבחן בחלק ההדרכה: מתודיקה, בטיחות, חוק, עמידה מול קהל.",
    items: [
      { title: "היבטים משפטיים של המקצוע", url: "https://docs.google.com/document/d/1SXY61_l9YKyZ-97zx22crwcwFZmcUXdSNJZdTHfV1Mk/edit?usp=sharing" },
      { title: "הסברה של מדינת ישראל", url: "https://docs.google.com/document/d/1pUr1mID-QyTKuMiww2ibfAsllHXtEB_Xy0pFfSbgKJ8/edit?usp=sharing" },
      { title: "תיירות בישראל", url: "https://docs.google.com/document/d/15lazd4aWzqei7h9qYQkPwHT0n4AKhnQdIVxAKcdB74s/edit?usp=sharing" },
      { title: "תיירות נגישה לאנשים עם מוגבלות", url: "https://docs.google.com/document/d/1x5sSE2Y-ptxiyq5OHajtA9oQ0JDi9bsVuUUH1905L-A/edit?usp=sharing" },
      { title: "בטחון ובטיחות בטיולים", url: "https://docs.google.com/document/d/1KRPkz3lsv038ysDbrCnBm2q5T3KXKyOR6mx1s0a9pFM/edit?usp=sharing" },
      { title: "מתודיקה של הדרכה", url: "https://docs.google.com/document/d/1pT8fji0ndFE62GbxRmvjNtqLIA7bzDlEtTqDyq47ngQ/edit?usp=sharing" },
      { title: "תדמית ועמידה בפני קהל", url: "https://docs.google.com/document/d/1I5hM96cw_KP96V-dIu8f2wDpVtYRx6Udc_p7X9qCzNA/edit?usp=sharing" },
      { title: "מיומנויות למידה וזכירה, הכנה למבחן הרישוי", url: "https://docs.google.com/document/d/1r6MdZWuhqN3Jti7fFRJfyFZlVKIQEXGG6-GNT_xO8ng/edit?usp=sharing" },
      { title: "מקורות מידע", url: "https://docs.google.com/document/d/1S6QCpa92JOKfsq_2ESuSQnWwaLlc57R8vO7T9lehmc4/edit?usp=sharing" },
    ],
  },
  {
    slug: "maps",
    title: "מצגות ומפות",
    description: "מפות Google ייעודיות ומצגות לנושאים שקשה לתפוס בלי לראות.",
    items: [
      { title: "מצגת חומות ירושלים", url: "https://docs.google.com/presentation/d/1692dQ6be9GsXgXOUKr47uwRKb6bKt4jJCaT3guk_np0/pub?start=true&loop=false&delayms=3000" },
      { title: "מצגת חומות עכו", url: "https://docs.google.com/presentation/d/1TRGG8aHic_fgpVW3S_jz3_2ZQqJA39LBb9wVKa2FTfU/pub?start=true&loop=false&delayms=3000" },
      { title: "מצגת ארץ ישראל - פלשתינה במאות 20 ו-21", url: "https://docs.google.com/presentation/d/17gg6pZJ7D623PiThhv8od0ULbzxtRZqfe9Q72FWkBvQ/present?usp=sharing" },
      { title: "מפת בתי כנסת קדומים", url: "https://maps.google.com/maps/ms?msid=208420713272214036416.0004d8939470f4a818929&msa=0&ll=32.184911,35.068359&spn=1.806087,2.1698" },
      { title: "מפת הדרכים לירושלים בתש\"ח", url: "https://maps.google.com/maps/ms?msid=208420713272214036416.0004f2c230244054e4944&msa=0&ll=31.887178,34.982529&spn=0.226504,0.271225" },
      { title: "מפת מבצרים צלבניים", url: "https://maps.google.com/maps/ms?msid=208420713272214036416.0004e92ed10016a27ecb7&msa=0&ll=32.42634,35.119171&spn=0.900663,1.0849" },
      { title: "מפת אתרי ביקור לצליינים נוצרים", url: "https://maps.google.com/maps/ms?msid=208420713272214036416.000503d069dd6875c01d0&msa=0&ll=32.282489,35.274353&spn=1.606813,1.834717" },
      { title: "מפת הוויה דולורוזה", url: "https://www.google.com/maps/d/viewer?mid=1UcW4kLrFpDOxuZU_rt6ktsWAn_x2kphJ&ll=31.779274008692518%2C35.231854&z=17" },
      { title: "מפת אתרי מורשת עולמית", url: "https://www.google.com/maps/d/edit?mid=zBn8Po9FnrI8.kNhJ6PUwN6_E&usp=sharing" },
    ],
  },
];
