// Auto-generated by tools/build_exams.py — do not edit by hand.
//
// The licensing syllabus, used as the subject axis of the question
// bank. `reading` links to the free summary for that subject.
export type Topic = {
  key: string;
  label: string;
  reading?: { title: string; url: string };
};

export const TOPICS: Topic[] = [
  { key: "minorities", label: "מיעוטים ועדות", reading: { title: "מיעוטים ופולקלור במדינת ישראל", url: "https://docs.google.com/document/d/1ROw5DUs_m3_VGlyusu6Jpe4fxFno_dDzKt01pRiWclc/edit?usp=sharing" } },
  { key: "christianity", label: "נצרות", reading: { title: "נצרות", url: "https://docs.google.com/document/d/11mCvlzEEE-5Vkvj1rKLzf4srcar8KilqjnZSCLoEeMA/edit?usp=sharing" } },
  { key: "islam", label: "אסלאם", reading: { title: "אסלאם", url: "https://docs.google.com/document/d/1wu4Gak-NGP9QRchoHu9FUzWoYURnRZwaFNU99CmyPCQ/edit?usp=sharing" } },
  { key: "judaism", label: "יהדות", reading: { title: "יהדות", url: "https://docs.google.com/document/d/1KM_ZdKJkXkm0rjNlXdCZmQsMvdZg8sRq59ntwfVOegk/edit?usp=sharing" } },
  { key: "prehistory", label: "פרהיסטוריה", reading: { title: "פרהיסטוריה בארץ ישראל", url: "https://docs.google.com/document/d/1USZJT7Jn4okKEgaza6bfFLbfLSJ6FUSD0w0qKPlkEQY/edit?usp=sharing" } },
  { key: "bible", label: "תקופת המקרא", reading: { title: "תקופת הבית הראשון וארכאולוגיה של התקופות הקדומות", url: "https://docs.google.com/document/d/113uXIGouRz2HF9Ad0DfUFz_Hbp_maJCj3AGOaA9Hvfo/edit?usp=sharing" } },
  { key: "second-temple", label: "בית שני והורדוס", reading: { title: "תקופת הבית השני", url: "https://docs.google.com/document/d/12UEzTJAj1lnbBBxUPA3e_4Fju9L0AqzVVmI6SrO9X8c/edit?usp=sharing" } },
  { key: "roman-byzantine", label: "רומית וביזנטית", reading: { title: "התקופה הרומית-ביזנטית, ארכאולוגיה קלאסית ויהודית", url: "https://docs.google.com/document/d/1_l62e2-qi-61dEZ9G1FMxjsVvfbEy4UkJocTdEUgtLY/edit?usp=sharing" } },
  { key: "early-islam", label: "ערבית קדומה ואומיית", reading: { title: "התקופה הערבית הקדומה", url: "https://docs.google.com/document/d/19oZPco0UaoDV-FAzc077R2BNGpohDm1ZcNrq6DBN0O4/edit?usp=sharing" } },
  { key: "crusader", label: "צלבנים", reading: { title: "התקופה הצלבנית", url: "https://docs.google.com/document/d/1E1VKYVRT19ykJRNgtRL0iVfM1B2MbFRDW9t6ZumD5ig/edit?usp=sharing" } },
  { key: "mamluk-ottoman", label: "ממלוכים ועות'מאנים", reading: { title: "התקופה המוסלמית-ערבית השנייה", url: "https://docs.google.com/document/d/1BXZjSgP0V6kdihVf4u2kBB6SX3YYeSij4kLXriiJjh8/edit?usp=sharing" } },
  { key: "modern-yishuv", label: "העת החדשה והיישוב", reading: { title: "העת החדשה", url: "https://docs.google.com/document/d/17WV-9umujOnu2RPloHsatC-0UCzSBlh384ZLudXdcc4/edit?usp=sharing" } },
  { key: "state", label: "מדינת ישראל ומלחמותיה", reading: { title: "מדינת ישראל מהקמתה ועד היום", url: "https://docs.google.com/document/d/1GEorjB-NrfPnO1Q843FFGT_tuDyZd5Y1RhCyRTQfykM/edit?usp=sharing" } },
  { key: "jerusalem", label: "ירושלים", reading: { title: "ירושלים לדורותיה", url: "https://docs.google.com/document/d/13dWXqUg3vYptUZybMbKOtJygXtPbqLHQgYOMYrPOHM0/edit?usp=sharing" } },
  { key: "geology", label: "גאולוגיה", reading: { title: "גאולוגיה וגאומורפולוגיה", url: "https://docs.google.com/document/d/1npLgmJSp3lAOVG47QtaTMHcqcqYZ6NV5pu7Uqunu_Dw/edit?usp=sharing" } },
  { key: "water-climate", label: "אקלים, מים ונחלים", reading: { title: "הידרולוגיה ומשאבי המים של ישראל", url: "https://docs.google.com/document/d/1WTcJ9ij3Yn5bnVByAVYTQdcCl8fI5U-HSMA8qzpi64A/edit?usp=sharing" } },
  { key: "flora-fauna", label: "צומח וחי", reading: { title: "הצומח בארץ ישראל", url: "https://docs.google.com/document/d/1JhBq5EEjARruNM-GASgHXE7zTymXYIrct9DvTCcUB28/edit?usp=sharing" } },
  { key: "geography", label: "גאוגרפיה ודרכים", reading: { title: "מבוא לארץ ישראל – דרכים", url: "https://docs.google.com/document/d/12RJ6BX1HSMBLwv8S76qm2rPqy4mBJkutwTnHatLeH9I/edit?usp=sharing" } },
  { key: "art-arch", label: "אמנות ואדריכלות", reading: { title: "סגנונות אדריכליים ואמנותיים", url: "https://docs.google.com/document/d/1zA1lhcVsIVCkBtK4UWkfk6DVHmWa1HkOQw4jFJuPO-w/edit?usp=sharing" } },
  { key: "tourism", label: "תיירות והמקצוע", reading: { title: "תיירות בישראל", url: "https://docs.google.com/document/d/15lazd4aWzqei7h9qYQkPwHT0n4AKhnQdIVxAKcdB74s/edit?usp=sharing" } },
];

export const TOPIC_LABELS: Record<string, string> = Object.fromEntries(
  TOPICS.map((t) => [t.key, t.label]),
);

export function topicOf(key?: string): Topic | undefined {
  return TOPICS.find((t) => t.key === key);
}
